# Note that flexo relies on the directory structure that is created in
# /var/cache/flexo during install. If you change this setting, copy the
# contents to the new directory and make sure user flexo has read- and
# write-access.
cache_directory = "/var/cache/flexo/pkg"

# The low speed limit in bytes per second.
# If the download speed falls below this threshold, a new mirror is selected,
# hoping that this will increase the download speed.
# For example, if your ISP provides 100 MBit per second, you might assume that
# mirrors are too slow if they do not utilize at least 80% of your bandwidth,
# so set this value to 80 MBit per second  = 10 MiB per second = 1024 * 1024 * 10 = 10485760
# Commenting this line will disable this feature.
# low_speed_limit = 128000

# The mirror will be switched if the downloaded speed has fallen below low_speed_limit
# for the given amount of seconds.
low_speed_time_secs = 3

# After the mirrorlist was fetched from a remote JSON endpoint and the mirrors have
# been tested and rated, the result (i.e., an ordered list of mirrors) will be persisted
# on the local file system so that it can serve as a backup in case there is no internet
# connectivity when flexo is started.
mirrorlist_fallback_file = "/var/cache/flexo/state/mirrorlist"

# The result of the latency tests are stored in a json file and retrieved when
# Flexo is restarted.
mirrorlist_latency_test_results_file = "/var/cache/flexo/state/latency_test_results.json"


# The port to listen on.
port = 7878

# The selection method to choose a mirror. Valid values are:
#   "auto": Flexo will attempt to find suitable mirrors automatically.
#           With this method, performance tests are run on the official mirrors
#           to select only sufficiently fast mirrors.
#   "predefined": To only choose the mirrors defined for the variable
#                 mirrors_predefined (see below).
mirror_selection_method = "auto"


# The meaning of this variable depends on the mirror_selection_method:
#   if mirror_selection_method = "auto", this list will be used as a fallback in
#   case flexo was not able to obtain a list of all official mirrors.
#   if mirror_selection_method = "predefined", flexo will only use mirrors from
#   this list.
# This list must not be empty if mirror_selection_method has been set to "predefined".
# Mirrors in this list should NOT include the $repo/os/$arch suffix, so you should add
# something like "http://archlinux.mirror.org/" or "https://mirror.org/archlinux/".
mirrors_predefined = []

# Various settings that apply if mirror_selection_method has been set to "auto".
[mirrors_auto]
    # The URI of the JSON endpoint that delivers information about all official mirrors.
    mirrors_status_json_endpoint = "https://www.archlinux.org/mirrors/status/json/"
    # The method to choose suitable mirrors automatically may not always work
    # perfectly. If one of the automatically chosen mirrors turns out to be slow or
    # unstable, add it to this list.
    mirrors_blacklist = [ ]
    # The maximum speed limit for all downloads. Leave it commented to allow
    # flexo to utilize all available bandwidth.
    # max_speed_limit = 102400
    # only use mirrors with HTTPS support.
    https_required = true
    # mirrors must support IPv4.
    ipv4 = true
    # mirrors must support IPv6. Notice that this setting does not force
    # connection establishment via IPv6, so having this setting enabled does not
    # cause any issues on IPv4-only clients.
    ipv6 = true
    # The maximum score allowed from a mirror. See
    # https://www.archlinux.org/mirrors/status/ for an explanation of this
    # metric.
    max_score = 2.5
    # When Flexo is started for the first time, latency tests run against *all*
    # mirrors, so the num_mirrors setting is ignored. The test results gained
    # from this first latency test are then used when Flexo is started again:
    # Instead of running the latency test against all mirrors from all
    # locations, we only choose mirrors at a location that scored well in the
    # previous latency test. For example: if num_mirrors is set to 3, and the
    # fastest 3 mirrors from the previous latency test where located in Germany,
    # France and Switzerland, then we will choose 3 mirrors from those 3
    # locations in our next latency test.
    # Increasing this parameter will also increase the startup time of flexo
    # (due to the increased number of latency tests), but it might also give you
    # a faster mirror.
    num_mirrors = 8
    # Valid values for this setting include "sort" and "random".  After the
    # mirrors have been filtered according to your chosen criteria (e.g. ipv6
    # supported, score not more than 2.5), you will most likely still have more
    # than num_mirrors mirrors. This setting determines the strategy for
    # choosing num_mirrors out of those mirrors. With "sort", the mirrors are
    # sorted by their score and the first num_mirrors mirrors are selected. With
    # "random", a random selection of num_mirrors are selected.  Choose "sort"
    # if you want to increase the likelihood of having a fast and up-to-date
    # mirror. Choose "random" if you want to avoid to always use the same
    # mirror, and instead balance the load among many mirrors.
    mirrors_random_or_sort = "sort"
    # timeout, in milliseconds, when testing the mirrors' performance.
    # Mirros which exceed the timeout will not be considered further, regardless
    # of their score.
    timeout = 350
